spring.application.name=travel-ai-assistant

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.stabilityai.api-key=${STABILITY_API_KEY}
spring.ai.stabilityai.image.model=stable-diffusion-xl-1024-v1-0


spring.datasource.url=jdbc:postgresql://localhost:5432/spring_ai
spring.datasource.username=postgres
spring.datasource.password=123456

spring.ai.chat.memory.repository.jdbc.initialize-schema=always
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=1536
spring.ai.mcp.client.enabled=true
spring.ai.mcp.client.streamable-http.connections.flights.url=http://localhost:8081
spring.ai.mcp.client.streamable-http.connections.hotels.url=http://localhost:8082

logging.level.org.springframework.ai=DEBUG
logging.level.io.modelcontextprotocol=DEBUG

app.weather.api-key=${WEATHER_API_KEY}
app.data.pdfs.path=data/pdfs
app.audio.upload-dir=data/audio
