spring.application.name=travel-ai-assistant

spring.ai.openai.api-key=${OPENAI_API_KEY}

spring.datasource.url=jdbc:postgresql://localhost:5432/spring_ai
spring.datasource.username=postgres
spring.datasource.password=123456

spring.ai.chat.memory.repository.jdbc.initialize-schema=always

logging.level.org.springframework.ai=DEBUG

app.weather.api-key=${WEATHER_API_KEY}
